# Generated by Django 4.2.6 on 2023-11-23 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GreenThumb", "0015_alter_company_contact_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="contact_info",
            new_name="Email_ID",
        ),
    ]
