# Generated by Django 4.2.6 on 2023-11-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GreenThumb", "0016_rename_contact_info_company_email_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="link",
        ),
        migrations.RemoveField(
            model_name="program",
            name="project_type",
        ),
        migrations.AlterField(
            model_name="program",
            name="program_name",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="program",
            name="supporting_docs",
            field=models.URLField(),
        ),
    ]
