# Generated by Django 4.2.6 on 2023-11-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GreenThumb", "0017_remove_program_link_remove_program_project_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="link",
            field=models.URLField(default="https://example.com"),
        ),
        migrations.AlterField(
            model_name="program",
            name="program_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="program",
            name="supporting_docs",
            field=models.TextField(),
        ),
    ]
