# Generated by Django 4.2.6 on 2023-11-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GreenThumb", "0018_program_link_alter_program_program_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="supporting_docs",
            field=models.JSONField(default=list),
        ),
    ]
