# Generated by Django 4.2.6 on 2023-11-24 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GreenThumb", "0019_alter_program_supporting_docs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="program",
            old_name="supporting_docs",
            new_name="ssupporting_docs",
        ),
    ]
