# Generated by Django 4.2.6 on 2023-11-24 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GreenThumb", "0020_rename_supporting_docs_program_ssupporting_docs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="program",
            old_name="ssupporting_docs",
            new_name="supporting_docs",
        ),
    ]
